// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRule'](arg1, arg2, arg3);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function GetCertStatus() {
  return window['go']['main']['App']['GetCertStatus']();
}

export function GetCustomCert() {
  return window['go']['main']['App']['GetCustomCert']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetNavConfig() {
  return window['go']['main']['App']['GetNavConfig']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function RegisterLogListener(arg1) {
  return window['go']['main']['App']['RegisterLogListener'](arg1);
}

export function SaveNavConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveNavConfig'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function SetCertConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetCertConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SetCustomCert(arg1, arg2) {
  return window['go']['main']['App']['SetCustomCert'](arg1, arg2);
}

export function StartServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartServer'](arg1, arg2, arg3);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function ToggleRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleRule'](arg1, arg2);
}

export function UnregisterLogListener() {
  return window['go']['main']['App']['UnregisterLogListener']();
}

export function UpdateRuleConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateRuleConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateRuleHeaders(arg1, arg2) {
  return window['go']['main']['App']['UpdateRuleHeaders'](arg1, arg2);
}
