// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {proxy} from '../models';

export function AddRule(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ClearLogs():Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function GetCustomCert():Promise<main.CustomCert>;

export function GetLogs():Promise<Array<proxy.RequestLog>>;

export function GetRules():Promise<Array<proxy.RouteRule>>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function SelectDirectory():Promise<string>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SetCustomCert(arg1:string,arg2:string):Promise<void>;

export function StartServer(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function StopServer():Promise<void>;

export function ToggleRule(arg1:string,arg2:boolean):Promise<void>;

export function UpdateRuleHeaders(arg1:string,arg2:Record<string, string>):Promise<void>;
