// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';
import {main} from '../models';

export function AddRule(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ClearLogs():Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function GetCertStatus():Promise<proxy.CertStatusInfo>;

export function GetCustomCert():Promise<main.CustomCert>;

export function GetLogs():Promise<Array<proxy.RequestLog>>;

export function GetNavConfig():Promise<main.NavConfig>;

export function GetRules():Promise<Array<proxy.RouteRule>>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function RegisterLogListener(arg1:any):Promise<void>;

export function SaveNavConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SetCertConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetCustomCert(arg1:string,arg2:string):Promise<void>;

export function StartServer(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function StopServer():Promise<void>;

export function ToggleRule(arg1:string,arg2:boolean):Promise<void>;

export function UnregisterLogListener():Promise<void>;

export function UpdateRuleConfig(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean,arg6:string,arg7:boolean,arg8:string):Promise<void>;

export function UpdateRuleHeaders(arg1:string,arg2:Record<string, string>):Promise<void>;
